spring:
  datasource:
    url: jdbc:mysql://localhost:3308/db_product
    username: user_product
    password: productpw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
