services:
  mysql:
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=testpw
      - MYSQL_DATABASE=testdb
    volumes:
      - ./db/scripts/:/docker-entrypoint-initdb.d
      - ./db/conf:/etc/mysql/conf.d
  redis:
    image: redis
    ports:
      - "6379:6379"